version: '3'

services:
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Fernand0101
      MYSQL_USER: FernandoFranco
      MYSQL_PASSWORD: Fernand0101
    ports:
      - "3306:3306"
    volumes:
    - mysql_data:/var/lib/mysql

  nodejs:
    image: node:latest
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    ports:
      - "3000:3000"

volumes:
  mysql_data: